### ISSUE TITLE
Also publish md5 or sha256/512 digest ?

### ISSUE THREAD

**Issue by abcfy2** [musl-cross/musl-cross#6]
Because of the big download archive size, I think it's better to also publish the md5 or sha256/512 digest to let the user verify download file is complete.

For example: https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.12%2B7_openj9-0.46.1

And: http://musl.cc/SHA512SUMS

Thanks.

**Comment by heiher** [comment]
Fixed by https://github.com/musl-cross/musl-cross/commit/9318b444e4e5f6b55eb422ca25d4fc5137f916a1
